import Header from "./Component/Header/Header";
import Footer from "./Component/Footer/Footer";
import Home from "./Component/Home/Home";
import About from "./Component/About/About";
import Contact from "./Component/Contact/Contact";
import Product from "./Component/Product/Product";
import Layout from "./Layout";
import Downloadcmp from "./Component/Download/Downloadcmp";
import SideBar from "./Component/SideBarComponent/SideBar";
import Github , {GithubInfo} from "./Component/Github/Github";
export { Home, Header, Footer, About, Contact, Product, Layout ,Downloadcmp, SideBar, Github,GithubInfo};
